openapi: 3.1.0
paths:
  /currencies:
    get:
      operationId: CurrenciesController_getCurrencies
      summary: Get list of available currencies
      parameters:
        - name: crypto
          required: false
          in: query
          description: Show crypto
          example: true
          schema:
            type: boolean
        - name: search
          required: false
          in: query
          description: Search query
          example: Рубль
          schema:
            type: string
      responses:
        '200':
          description: List of available currencies
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListDto'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CurrencyDto'
      tags:
        - Currencies
  /currencies/{base}:
    get:
      operationId: CurrenciesController_getCurrency
      summary: Get currency detailed information
      parameters:
        - name: base
          required: true
          in: path
          description: Currency unique code
          example: AED
          schema:
            type: string
      responses:
        '200':
          description: Currency detailed information
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataDto'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CurrencyDetailedDto'
        '404':
          description: Currency not found
      tags:
        - Currencies
  /currencies/{base}/latest:
    get:
      operationId: CurrenciesController_getCurrencyLatest
      summary: Get currency with latest rates
      parameters:
        - name: base
          required: true
          in: path
          description: Currency unique code
          example: AED
          schema:
            type: string
        - name: codes
          required: false
          in: query
          description: List of currency codes
          example:
            - EUR
            - AED
            - RUB
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Currency with latest available rate data
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataDto'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CurrencyWithLatestRatesDto'
        '404':
          description: Currency not found
      tags:
        - Currencies
  /currencies/{base}/daily:
    get:
      operationId: CurrenciesController_getCurrencyDaily
      summary: Get currency with rates by date
      parameters:
        - name: base
          required: true
          in: path
          description: Currency unique code
          example: AED
          schema:
            type: string
        - name: date
          required: false
          in: query
          description: Date
          example: '2021-10-04'
          schema:
            type: string
        - name: codes
          required: false
          in: query
          description: List of currency codes
          example:
            - EUR
            - AED
            - RUB
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Currency with rate data
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataDto'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CurrencyWithRatesDto'
        '404':
          description: Currency not found
      tags:
        - Currencies
  /currencies/{base}/historical:
    get:
      operationId: CurrenciesController_getCurrencyHistoricalRates
      summary: 'Get currency daily rates by provided time series '
      description: Time range should be not bigger than 365 days, otherwise use /monthly
      parameters:
        - name: base
          required: true
          in: path
          description: Currency unique code
          example: AED
          schema:
            type: string
        - name: start
          required: true
          in: query
          description: Start date
          example: '2021-10-04'
          schema:
            type: string
        - name: end
          required: true
          in: query
          description: End date
          example: '2021-10-04'
          schema:
            type: string
        - name: codes
          required: false
          in: query
          description: List of currency codes
          example:
            - EUR
            - AED
            - RUB
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Currency with historical rate data
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataDto'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CurrencyHistoricalRatesDto'
        '400':
          description: Start date should be less than end date
        '404':
          description: Currency or rates for selected range not found
      tags:
        - Currencies
  /currencies/{base}/monthly:
    get:
      operationId: CurrenciesController_getCurrencyMonthlyRates
      summary: Get currency monthly rates by provided time series
      parameters:
        - name: base
          required: true
          in: path
          description: Currency unique code
          example: AED
          schema:
            type: string
        - name: start
          required: true
          in: query
          description: Start date
          example: '2021-10-04'
          schema:
            type: string
        - name: end
          required: true
          in: query
          description: End date
          example: '2021-10-04'
          schema:
            type: string
        - name: codes
          required: false
          in: query
          description: List of currency codes
          example:
            - EUR
            - AED
            - RUB
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Currency with monthly rate data
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataDto'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CurrencyMonthlyRatesDto'
        '400':
          description: Start date should be less than end date
        '404':
          description: Currency or rates for selected range not found
      tags:
        - Currencies
  /rates/latest:
    get:
      operationId: RatesController_getLatestRates
      summary: Get latest rates for selected currencies
      parameters:
        - name: codes
          required: true
          in: query
          description: List of currency codes, at least 1, maximum 10
          example:
            - EUR
            - AED
            - RUB
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Currency with latest available rate data
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListDto'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CurrencyWithLatestRatesDto'
      tags:
        - Rates
info:
  title: API Documentation
  description: OpenAPI specification for Exchange It.
  version: 0.0.3
tags: [ ]
servers: [
  {
    url: 'https://api.exchangeit.app/'
  }
]
components:
  schemas:
    CopyrightDto:
      type: object
      properties:
        title:
          type: string
          example: Thanks for using Exchange It API
        description:
          type: string
          example: Some description text
        url:
          type: string
          example: https://exchangeit.app/
        email:
          type: string
          example: hello@exchangeit.app
      required:
        - title
        - description
        - url
        - email
    ListMetaDto:
      type: object
      properties:
        total:
          type: number
          description: Total items in list
          example: 10
        perPage:
          type: number
          description: Items per page
          example: 30
        page:
          type: number
          description: Current page number, where 0 is first page
          example: 0
        nextPage:
          type: number
          description: Next page number or null if no next page
          example: 1
          nullable: true
        totalPages:
          type: number
          description: Total pages
          example: 1
      required:
        - total
        - page
    ListDto:
      type: object
      properties:
        copyright:
          allOf:
            - $ref: '#/components/schemas/CopyrightDto'
        meta:
          allOf:
            - $ref: '#/components/schemas/ListMetaDto'
        data:
          type: array
          items:
            type: string
      required:
        - meta
        - data
    CurrencyDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
      required:
        - code
        - title
    DataDto:
      type: object
      properties:
        copyright:
          allOf:
            - $ref: '#/components/schemas/CopyrightDto'
        data:
          type: object
          nullable: true
      required:
        - data
    CurrencyDetailedDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
        description:
          type: string
          description: Currency description
          example: >-
            The United States dollar (or American dollar) is the official
            currency (money) of the United States of America. It is also used in
            some other countries outside the US. It is the standard currency for
            international markets selling goods such as gold and oil (petrol).
            When writing, the symbol for the American dollar is the dollar sign
            ($). Dollars can also be known as USD (standing for 'U.S. dollar').
          nullable: true
        localizedTitle:
          type: object
          description: Localized titles
          additionalProperties:
            type: string
            description: Localized title
        localizedDescription:
          type: object
          description: Localized descriptions
          additionalProperties:
            type: string
            description: Localized description
        crypto:
          type: boolean
          description: Is crypto currency?
          example: false
        symbol:
          type: string
          description: Currency symbol
          example: ₺
          nullable: true
        year:
          type: number
          description: Year of introduction
          example: 2010
          nullable: true
        url:
          type: string
          description: URL to currency (for example link to crypto currency)
          example: https://currency.com
          nullable: true
      required:
        - code
        - title
        - description
        - localizedTitle
        - localizedDescription
        - crypto
        - symbol
        - year
        - url
    CurrencyRateWithDateDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: RUB
        rate:
          type: number
          description: Currency rate
          example: 0.0089
        date:
          type: string
          description: Date in YYYY-mm-dd format
          example: '2021-10-04'
        fluctuation:
          type: number
          description: Currency fluctuation with previous rate
          example: -0.02
      required:
        - code
        - rate
        - date
        - fluctuation
    CurrencyWithLatestRatesDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
        rates:
          description: Currency latest rates
          type: array
          items:
            $ref: '#/components/schemas/CurrencyRateWithDateDto'
      required:
        - code
        - title
        - rates
    CurrencyRateDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: RUB
        rate:
          type: number
          description: Currency rate
          example: 0.0089
      required:
        - code
        - rate
    CurrencyWithRatesDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
        date:
          type: string
          description: Date in YYYY-mm-dd format
          example: '2021-10-04'
        rates:
          description: Currency rates
          type: array
          items:
            $ref: '#/components/schemas/CurrencyRateDto'
      required:
        - code
        - title
        - date
        - rates
    CurrencyHistoricalRateDto:
      type: object
      properties:
        date:
          type: string
          description: Date in YYYY-mm-dd format
          example: '2021-10-04'
        rates:
          description: Currency rates
          type: array
          items:
            $ref: '#/components/schemas/CurrencyRateDto'
      required:
        - date
        - rates
    CurrencyHistoricalRatesDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
        start:
          type: string
          description: Start date in YYYY-MM-DD format
          example: '2021-10-04'
        end:
          type: string
          description: End date in YYYY-MM-DD format
          example: '2021-10-04'
        historical:
          description: Historical rates for selected range
          type: array
          items:
            $ref: '#/components/schemas/CurrencyHistoricalRateDto'
      required:
        - code
        - title
        - start
        - end
        - historical
    CurrencyMonthRateDto:
      type: object
      properties:
        month:
          type: string
          description: Month in YYYY-mm format
          example: 2021-10
        rates:
          description: Currency rates
          type: array
          items:
            $ref: '#/components/schemas/CurrencyRateDto'
      required:
        - month
        - rates
    CurrencyMonthlyRatesDto:
      type: object
      properties:
        code:
          type: string
          description: Unique currency code
          example: AED
        title:
          type: string
          description: Currency title
          example: United Arab Emirates Dirham
        start:
          type: string
          description: Start date in YYYY-MM format
          example: 2021-10
        end:
          type: string
          description: End date in YYYY-MM format
          example: 2021-10
        monthly:
          description: Monthly rates for selected range
          type: array
          items:
            $ref: '#/components/schemas/CurrencyMonthRateDto'
      required:
        - code
        - title
        - start
        - end
        - monthly
